apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: workload-identity.yaml
images:
  - name: web-ui
    newName: example.azurecr.io/web-ui
    newTag: latest
  - name: banking-api
    newName: example.azurecr.io/banking-api
    newTag: latest
  - name: ai-service
    newName: example.azurecr.io/ai-service
    newTag: latest
